# Generated by Django 4.2.2 on 2023-07-05 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Portal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=100, null=True)),
                ('jname', models.CharField(max_length=100, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('duration', models.CharField(max_length=300, null=True)),
                ('work_type', models.CharField(max_length=300, null=True)),
                ('gender', models.CharField(max_length=100)),
                ('requirements', models.CharField(max_length=300, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('date', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(null=True, upload_to='profile')),
                ('loginid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
