# Generated by Django 4.2.2 on 2023-07-14 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_duration_job_portal_ex_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_portal',
            name='work_type',
        ),
        migrations.AlterField(
            model_name='job_portal',
            name='cid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.company_reg'),
        ),
        migrations.CreateModel(
            name='Job_Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('image', models.FileField(null=True, upload_to='profile')),
                ('cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.company_reg')),
                ('jid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.job_portal')),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.userregistration')),
            ],
        ),
    ]
