# Generated by Django 4.2.2 on 2023-07-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_job_portal_work_type_alter_job_portal_cid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_portal',
            name='cid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
