# Generated by Django 4.2.2 on 2023-07-14 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_job_portal_cid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_application',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='job_application',
            name='jid',
        ),
        migrations.RemoveField(
            model_name='job_application',
            name='uid',
        ),
        migrations.DeleteModel(
            name='Company_reg',
        ),
        migrations.DeleteModel(
            name='Job_Application',
        ),
        migrations.DeleteModel(
            name='Job_Portal',
        ),
    ]
