# Generated by Django 4.2.2 on 2023-07-14 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_job_application_cid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(max_length=300, null=True)),
                ('gender', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='profile')),
                ('loginid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
