# Generated by Django 4.2.2 on 2023-07-14 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_company_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Portal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jname', models.CharField(max_length=100, null=True)),
                ('salary', models.CharField(blank=True, max_length=300, null=True)),
                ('ex_level', models.CharField(max_length=300, null=True)),
                ('job_type', models.CharField(max_length=300, null=True)),
                ('location', models.CharField(max_length=300, null=True)),
                ('gender', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=300, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('date', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(null=True, upload_to='profile')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.company_reg')),
            ],
        ),
        migrations.CreateModel(
            name='Job_Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('image', models.FileField(null=True, upload_to='profile')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.company_reg')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.job_portal')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.userregistration')),
            ],
        ),
    ]
