# Generated by Django 4.2.2 on 2023-07-15 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_job_portal_job_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_portal',
            old_name='company',
            new_name='cid',
        ),
    ]
