# Generated by Django 4.2.2 on 2023-07-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_company_job_portal_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_portal',
            name='cid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
