# Generated by Django 4.2.2 on 2023-07-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_job_portal_cid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_application',
            old_name='description',
            new_name='education',
        ),
        migrations.RenameField(
            model_name='job_application',
            old_name='image',
            new_name='resume',
        ),
        migrations.AddField(
            model_name='job_application',
            name='field',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
