# Generated by Django 4.2.2 on 2023-07-17 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_job_portal_cid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company_reg',
            new_name='Client_reg',
        ),
    ]
