# Generated by Django 4.2.2 on 2023-07-17 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rename_company_reg_client_reg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_portal',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='job_portal',
            name='location',
        ),
        migrations.RemoveField(
            model_name='job_portal',
            name='qualification',
        ),
    ]
