# Generated by Django 4.2.2 on 2023-07-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_job_portal_gender_remove_job_portal_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_application',
            name='status',
            field=models.FileField(default='Applied', null=True, upload_to=''),
        ),
    ]
