# Generated by Django 4.2.2 on 2023-07-18 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_job_application_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdate', models.CharField(blank=True, max_length=300, null=True)),
                ('ldate', models.CharField(max_length=300, null=True)),
                ('title', models.CharField(max_length=300, null=True)),
                ('status', models.FileField(default='Added', null=True, upload_to='')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.client_reg')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.userregistration')),
            ],
        ),
    ]
