# Generated by Django 4.2.2 on 2023-07-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='company',
            new_name='sender',
        ),
        migrations.AddField(
            model_name='message',
            name='reciveremail',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='senderemail',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
