# Generated by Django 4.2.2 on 2023-07-22 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_rename_user_message_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.job_portal'),
        ),
    ]
