# Generated by Django 4.2.2 on 2023-07-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_work_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='desc',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
