# Generated by Django 4.2.2 on 2023-07-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_work_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='status',
            field=models.FileField(default='Assigned', null=True, upload_to=''),
        ),
    ]
