# Generated by Django 4.2.2 on 2023-07-22 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_work_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistration',
            old_name='gender',
            new_name='title',
        ),
    ]
