# Generated by Django 4.2.2 on 2023-07-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_rename_gender_userregistration_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='payment',
            field=models.FileField(default='Not_Paid', null=True, upload_to=''),
        ),
    ]
