# Generated by Django 4.2.2 on 2023-07-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_work_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='amount',
            field=models.CharField(default='Not_defined', max_length=300, null=True),
        ),
    ]
