# Generated by Django 4.2.2 on 2023-07-24 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_work_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed', models.EmailField(max_length=100, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.client_reg')),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.userregistration')),
                ('wid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.work')),
            ],
        ),
    ]
