# Generated by Django 4.2.2 on 2023-07-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='Rating',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
