# Generated by Django 4.2.2 on 2023-07-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_userregistration_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='Tavg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
