# Generated by Django 4.1.2 on 2024-02-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_feedback_tavg'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='resume',
            field=models.FileField(null=True, upload_to='resume'),
        ),
    ]
