# Generated by Django 4.1.2 on 2024-02-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_userregistration_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('url', models.CharField(max_length=100, null=True)),
                ('desc', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
