# Generated by Django 5.1.6 on 2025-03-22 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_userfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeedback',
            name='cid',
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='wid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.work'),
        ),
    ]
