# Generated by Django 5.1.6 on 2025-03-22 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_remove_userfeedback_cid_userfeedback_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='wid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.job_portal'),
        ),
    ]
