# Generated by Django 5.1.6 on 2025-03-26 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_application',
            name='interviewdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='job_application',
            name='interviewtime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='job_application',
            name='message',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('salary', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(default='Requested', max_length=100, null=True)),
                ('interviewdate', models.DateField(null=True)),
                ('interviewtime', models.TimeField(null=True)),
                ('message', models.CharField(max_length=300, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.client_reg')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.userregistration')),
            ],
        ),
    ]
