# Generated by Django 5.1.6 on 2025-03-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_useradminchat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useradminchat',
            old_name='message',
            new_name='adminmessage',
        ),
        migrations.AddField(
            model_name='useradminchat',
            name='usermessage',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
