# Generated by Django 5.1.6 on 2025-03-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_rename_message_useradminchat_adminmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='month',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='status',
            field=models.CharField(default='Pending', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='year',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
