# Generated by Django 5.1.6 on 2025-03-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_login_month_login_status_login_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_amount', models.CharField(max_length=100, null=True)),
                ('client_amount', models.CharField(max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='login',
            name='month',
        ),
        migrations.RemoveField(
            model_name='login',
            name='year',
        ),
        migrations.AddField(
            model_name='login',
            name='pdate',
            field=models.DateField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='amount',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
