# Generated by Django 5.1.6 on 2025-04-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_allpayments'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_reg',
            name='proof',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
